# Generated by Django 3.1.7 on 2021-03-30 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=64)),
                ('last_name', models.CharField(default=None, max_length=64)),
                ('second_name', models.CharField(default=None, max_length=64)),
                ('finance', models.FloatField(default=0)),
                ('mail', models.CharField(default=None, max_length=64)),
                ('password', models.CharField(default=None, max_length=255)),
            ],
        ),
    ]
