# Generated by Django 3.1.7 on 2021-03-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210330_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hash',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
