# Generated by Django 3.1.7 on 2021-03-30 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210330_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='salt',
        ),
    ]
