# Generated by Django 3.1.7 on 2021-03-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210330_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hash',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
