# Generated by Django 3.1.7 on 2021-03-30 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210330_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='finance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hash',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='salt',
        ),
        migrations.RemoveField(
            model_name='user',
            name='second_name',
        ),
    ]
