# Generated by Django 3.1.7 on 2021-03-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210330_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='finance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='hash',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='salt',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='second_name',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
