# Generated by Django 3.1.7 on 2021-03-30 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210330_1815'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
