# Generated by Django 3.1.7 on 2021-03-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0010_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=64)),
                ('last_name', models.CharField(default=None, max_length=64)),
                ('second_name', models.CharField(default=None, max_length=64)),
                ('email', models.CharField(default=None, max_length=64)),
                ('hash', models.CharField(default=None, max_length=255)),
                ('salt', models.CharField(default=None, max_length=255)),
                ('finance', models.FloatField(default=0)),
            ],
        ),
    ]
